### ISSUE TITLE
error with stdin - termios.error (with patch)

### ISSUE THREAD

**Issue by mlauke** [mnaberez/py65#46] opened 2018-09-27 14:00 UTC
hi,

we have some problems with the termios module. sometimes we get a error code 25 as you can see below.
Py65 Monitor
        PC  AC XR YR SP NV-BDIZC`
65C02: 0000 00 00 00 ff 00110000
.Wrote +2955 bytes from $e800 to $f38a
        PC  AC XR YR SP NV-BDIZC
65C02: 0000 00 00 00 ff 00110000
.Error: <class 'termios.error'>, (**25, 'Inappropriate ioctl for device'**): file: /usr/lib/python3.6/site-packages/py65/utils/**console.py line: 54**
...

i've created a patch that "works for me". at least i just catch the termios.error in console.getch_noblock() and answer "nothing". within monitor and _install_mpu_observers.getc i also return nothing if there where no char read. maybe thats not a good solution, but sometimes termios behaves very odd.

problem is reproducable: native linux and cygwin, python3.6

[termios.patch.gz](https://github.com/mnaberez/py65/files/2424398/termios.patch.gz)

cheers

**Comment by mnaberez** [comment] 2018-09-27 16:33
Contents of `termios.patch.gz` from above:

```diff
:100644 100644 b63db62 0000000 M py65/monitor.py
:100644 100644 eb15df0 0000000 M py65/utils/console.py

diff --git a/py65/monitor.py b/py65/monitor.py
index b63db62..096f974 100644
--- a/py65/monitor.py
+++ b/py65/monitor.py
@@ -235,9 +235,8 @@ class Monitor(cmd.Cmd):
             char = console.getch_noblock(self.stdin)
             if char:
                 byte = ord(char)
-            else:
-                byte = 0
-            return byte
+                return byte
+            return
 
         m = ObservableMemory(subject=self.memory, addrWidth=self.addrWidth)
         m.subscribe_to_write([self.putc_addr], putc)
diff --git a/py65/utils/console.py b/py65/utils/console.py
index eb15df0..4984a5a 100644
--- a/py65/utils/console.py
+++ b/py65/utils/console.py
@@ -50,8 +50,10 @@ else:
         """
 
         fd = stdin.fileno()
-
-        oldterm = termios.tcgetattr(fd)
+        try:
+           oldterm = termios.tcgetattr(fd)
+        except termios.error:
+           return
         newattr = oldterm[:]
         newattr[3] = newattr[3] & ~termios.ICANON & ~termios.ECHO
         termios.tcsetattr(fd, termios.TCSANOW, newattr)
```

**Comment by mnaberez** [comment] 2018-09-29 06:05
> problem is reproducable: native linux and cygwin, python3.6

Can you please provide instructions for how to reproduce it?  I have not been able to observe this error.

**Comment by mnaberez** [comment] 2018-10-06 20:04
I have committed a version of your patch in 7ed4d95885f91b70c5814ec308d5d2eb78d13f23.  Please let me know if this fixes the problems that you were having running the Steckschwein tests.  We can continue to iterate on it if not.  Thanks for the report!

About my changes to your patch: 
I did not commit the patch directly because of the change in return types.  The [`getc()` function](https://github.com/mnaberez/py65/blob/7ed4d95885f91b70c5814ec308d5d2eb78d13f23/py65/monitor.py#L239) in `monitor.py` originally returned `0` but you changed it to `None`.  This is will likely cause an error later because the return value is passed to the 6502 emulation code (it will be stored in a memory or a register).  Similarly, in the [`getch_noblock()` function](https://github.com/mnaberez/py65/blob/7ed4d95885f91b70c5814ec308d5d2eb78d13f23/py65/utils/console.py#L48-L49) in `utils.py`, the function was documented to return an empty string but you changed it to return `None` for the case of the `termios` error.  It would still return an empty string for the normal case.  I made it return an empty string in both cases.

**Comment by mlauke** [comment] 2018-10-07 16:15
hi, and many thx for the fix. it now works perfectly with our tests. the problem does not appear anymore.

**Comment by mnaberez** [comment] 2018-10-12 17:33
Reopening.  The issue was accidentally by GitHub when I committed cd673d50d1acc3cb3f5d169a7e807fdf812bf7c8 to revert 7ed4d95885f91b70c5814ec308d5d2eb78d13f23.

**Comment by SamCoVT** [comment] 2018-11-01 21:33
I'll second the request for specific steps to reproduce this bug, as I am currently playing with that section of code myself.

**Comment by SamCoVT** [comment] 2019-01-03 15:48
I've been able to recreate this issue and determine the problem.  It's caused when the "stdin" being used by the monitor is not a pty (eg. when it's being redirected from a file or pipe).  It can also be caused when running the monitor "inside" of another program, such as an IDE, rather than directly from a shell.
mlauke's thought of catching the error and ignoring it is reasonable under the circumstances that cause it, and I will add that to the routines I am working on in utils.console.

**Comment by mnaberez** [comment] 2024-04-13 00:21
> I will add that to the routines I am working on in utils.console.

Closing this pull request since those routines have since been merged.

**Closed by mnaberez** 2024-04-13 00:21 UTC
